```{r}
defaultdir <- getwd()
dir.create("graphs")
# "/graphs/"
# setwd(paste(defaultdir,"/graphs/", sep = ""))
dir.create("tables")
# setwd(paste(defaultdir,"/tables/", sep = ""))


```

```{r, loading packages, include=TRUE, echo=FALSE}
#Adding the required packages for this file. Don't change the current order, and add new packages to the first.
packages <- c(
  "ggplot2", 
  "tidyverse", 
  "dplyr",
  "corrplot",
  "Hmisc"
  ) 
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
  lapply(packages, library, character.only = TRUE)
} else {
  lapply(packages, library, character.only = TRUE)
}
#Adding the required packages for this file. Don't change the current order, and add new packages to the first.

```

```{r}
setwd(paste(defaultdir,"/tables/", sep = ""))
dir.create("Combined_MarshClass")
# setwd(paste(defaultdir,"/tables/Combined_MarshClass/", sep = ""))



## Combine MarshClass and Coordinates together
setwd(defaultdir)

for (i in 2006:2019){
  MarshClass = read.csv(paste(defaultdir,"/data/MarshClass/",i,".csv",sep=""),
                     header = TRUE,sep = ",")
  MarshClass_Coordinates = read.csv(paste(defaultdir,"/data/MarshClass/",i, "_Coordinates.csv",sep=""),
                          header = TRUE,sep = ",")
  names(MarshClass)[1] <- "Site_id"
  names(MarshClass_Coordinates)[1] <- "Site_id"
  a <- inner_join(MarshClass_Coordinates, MarshClass, by = "Site_id")
  a <- a[,c(-4,-8)]
  write.csv(a, paste(defaultdir,"/tables/Combined_MarshClass/",i ,"_Combined_MarshClass.csv",sep=""), row.names = FALSE)
}
remove(a, b, i, j, MarshClass, MarshClass_Coordinates)
## Combine MarshClass and Coordinates together

## Add all years' observation together
setwd(paste(defaultdir,"/tables/Combined_MarshClass/", sep = ""))
a <- read.csv("2006_Combined_MarshClass.csv", header = TRUE,sep = ",")
for(i in 2006:2018){
  a <- rbind(a, read.csv(paste(i+1, "_Combined_MarshClass.csv", sep = ""), header = TRUE,sep = ","))
}
write.csv(a, paste(defaultdir,"/tables/Combined_MarshClass/","Total" ,"_Combined_MarshClass.csv",sep=""), row.names = FALSE)
remove(a, b, i)
## Add all years' observation together

```

