```{r}
defaultdir <- getwd()
dir.create("graphs")
# "/graphs/"
# setwd(paste(defaultdir,"/graphs/", sep = ""))
dir.create("tables")
# setwd(paste(defaultdir,"/tables/", sep = ""))


```

```{r, loading packages, include=TRUE, echo=FALSE}
#Adding the required packages for this file. Don't change the current order, and add new packages to the first.
packages <- c(
  "ggplot2", 
  "tidyverse", 
  "dplyr",
  "corrplot",
  "Hmisc",
  "stringr"
  ) 
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
  lapply(packages, library, character.only = TRUE)
} else {
  lapply(packages, library, character.only = TRUE)
}
#Adding the required packages for this file. Don't change the current order, and add new packages to the first.

```

```{r}
setwd(paste(defaultdir,"/tables/", sep = ""))
dir.create("Combined_Hydro_filtered")
setwd(defaultdir)

for (i in 2006:2019){
  a <- read.csv(paste(defaultdir,"/tables/Combined_Hydro/",i,"_Combined_Hydro.csv",sep=""),
                     header = TRUE,sep = ",")
  a <- filter(a, str_detect(Site_id, "CRMS"))
  a <- a[,c(-2,-3)]
  a$Site_id <- gsub("-.*", "\\1", a$Site_id )
  a <- a[!duplicated(a$Site_id),]
  a$Site_id <- paste(a$Site_id, "_", a$year, sep = "")
  write.csv(a, paste(defaultdir,"/tables/Combined_Hydro_filtered/",i ,"_Combined_Hydro_filtered.csv",sep=""), row.names = FALSE)
}
remove(a, i)

## Add all years' observation together
setwd(paste(defaultdir,"/tables/Combined_Hydro_filtered/", sep = ""))
a <- read.csv("2006_Combined_Hydro_filtered.csv", header = TRUE,sep = ",")
for(i in 2006:2018){
  a <- rbind(a, read.csv(paste(i+1, "_Combined_Hydro_filtered.csv", sep = ""), header = TRUE,sep = ","))
}
write.csv(a, paste(defaultdir,"/tables/Combined_Hydro_filtered/","Total" ,"_Combined_Hydro_filtered.csv",sep=""), row.names = FALSE)
remove(a, b, i)
## Add all years' observation together



```



