```{r}
defaultdir <- getwd()
dir.create("graphs")
# "/graphs/"
# setwd(paste(defaultdir,"/graphs/", sep = ""))
dir.create("tables")
# setwd(paste(defaultdir,"/tables/", sep = ""))


```

```{r, loading packages, include=TRUE, echo=FALSE}
#Adding the required packages for this file. Don't change the current order, and add new packages to the first.
packages <- c(
  "ggplot2", 
  "tidyverse", 
  "dplyr",
  "corrplot",
  "Hmisc", 
  "gridExtra"
  ) 
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
  lapply(packages, library, character.only = TRUE)
} else {
  lapply(packages, library, character.only = TRUE)
}
#Adding the required packages for this file. Don't change the current order, and add new packages to the first.

```


```{r}
setwd(paste(defaultdir,"/tables/", sep = ""))
dir.create("Average_VVI_Salinity")
setwd(defaultdir)

for(i in 2006:2019){
  a = read.csv(paste(defaultdir, 
                     "/tables/Combined_VVI_MarshClass_HydroFiltered/", 
                     i,"_Combined_VVI_MarshClass_HydroFiltered.csv",sep=""),
                     header = TRUE,sep = ",") 
  a <- subset(a, a$Marsh_Class != "Swamp") #Removing swamp from the dataaset, casuse there are no data for swamp.
  a <- a[, c(2, 6 , 20, 23)]
  a <- a %>%
  group_by(Marsh_Class) %>%
  summarise_at(vars(), funs(mean(., na.rm=TRUE))) 
  write.csv(a, paste(defaultdir,"/tables/Average_VVI_Salinity/",i ,"_Average_VVI_Salinity.csv",sep=""), row.names = FALSE)
}

setwd(paste(defaultdir,"/tables/Average_VVI_Salinity/", sep = ""))
a <- read.csv(paste(2006, "_Average_VVI_Salinity.csv", sep = ""), header = TRUE,sep = ",")
for(i in 2006:2018){
  a <- rbind(a, read.csv(paste(i+1, "_Average_VVI_Salinity.csv", sep = ""), header = TRUE,sep = ","))
}
write.csv(a, paste(defaultdir,"/tables/Average_VVI_Salinity/" ,"Total_Average_VVI_Salinit.csv",sep=""), row.names = FALSE)

remove(a)
```




```{r}
setwd(defaultdir)
AveVVI_vs_AveSal <- read.csv(paste(defaultdir,"/tables/Average_VVI_Salinity/", "Total_Average_VVI_Salinit.csv",sep=""),
                          header = TRUE,sep = ",")
names(AveVVI_vs_AveSal)[4] <- "Average_Salinity"
names(AveVVI_vs_AveSal)[3] <- "Average_VVI"
AveVVI_vs_AveSal_plot <- ggplot(AveVVI_vs_AveSal,aes(x=Average_VVI,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Salinity", y= "Average Vegetation Volum Index (VVI)")  + 
  guides(color=guide_legend("Marsh Types"), shape = guide_legend("Marsh Types"))

AveVVI_vs_AveSal_plot
#################

AveVVI_vs_AveSal_Brackish <- subset(AveVVI_vs_AveSal, Marsh_Class == "Brackish")
AveVVI_vs_AveSal_plot_Brackish <- ggplot(AveVVI_vs_AveSal_Brackish,aes(x=Average_VVI,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Salinity", y= "Average Vegetation Volum Index (VVI)") 

AveVVI_vs_AveSal_plot_Brackish
#################

AveVVI_vs_AveSal_Fresh <- subset(AveVVI_vs_AveSal, Marsh_Class == "Fresh")
AveVVI_vs_AveSal_plot_Fresh <- ggplot(AveVVI_vs_AveSal_Fresh,aes(x=Average_VVI,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Salinity", y= "Average Vegetation Volum Index (VVI)") 

AveVVI_vs_AveSal_plot_Fresh
#################

AveVVI_vs_AveSal_Intermediate <- subset(AveVVI_vs_AveSal, Marsh_Class == "Intermediate")
AveVVI_vs_AveSal_plot_Intermediate <- ggplot(AveVVI_vs_AveSal_Intermediate,aes(x=Average_VVI,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Salinity", y= "Average Vegetation Volum Index (VVI)") 

AveVVI_vs_AveSal_plot_Intermediate
#################

AveVVI_vs_AveSal_Saline <- subset(AveVVI_vs_AveSal, Marsh_Class == "Saline")
AveVVI_vs_AveSal_plot_Saline <- ggplot(AveVVI_vs_AveSal_Saline,aes(x=Average_VVI,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Salinity", y= "Average Vegetation Volum Index (VVI)") 

AveVVI_vs_AveSal_plot_Saline
#################


```

```{r}
setwd(defaultdir)
Brackish <- subset(AveVVI_vs_AveSal, Marsh_Class == "Brackish")

Brackish_plot <- ggplot(Brackish,aes(x=veg_year,y=Average_VVI)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Year", y= "Average Vegetation Volum Index (VVI)") + 
  guides(color=guide_legend("Marsh Type"), shape = guide_legend("Marsh Type"))

Brackish_plot
###########

Fresh <- subset(AveVVI_vs_AveSal, Marsh_Class == "Fresh")

Fresh_plot <- ggplot(Fresh,aes(x=veg_year,y=Average_VVI)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Year", y= "Average Vegetation Volum Index (VVI)") + 
  guides(color=guide_legend("Marsh Type"), shape = guide_legend("Marsh Type"))
Fresh_plot

###########
Intermediate <- subset(AveVVI_vs_AveSal, Marsh_Class == "Intermediate")

Intermediate_plot <- ggplot(Intermediate,aes(x=veg_year,y=Average_VVI)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Year", y= "Average Vegetation Volum Index (VVI)") + 
  guides(color=guide_legend("Marsh Type"), shape = guide_legend("Marsh Type"))
Intermediate_plot

###########
Saline <- subset(AveVVI_vs_AveSal, Marsh_Class == "Saline")

Saline_plot <- ggplot(Saline,aes(x=veg_year,y=Average_VVI)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Year", y= "Average Vegetation Volum Index (VVI)") + 
  guides(color=guide_legend("Marsh Type"), shape = guide_legend("Marsh Type"))
Saline_plot




```

```{r}
setwd(defaultdir)
Brackish <- subset(AveVVI_vs_AveSal, Marsh_Class == "Brackish")

Brackish_plot <- ggplot(Brackish,aes(x=veg_year,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Year", y= "Average Salinity") + 
  guides(color=guide_legend("Marsh Type"), shape = guide_legend("Marsh Type"))
Brackish_plot
###########

Fresh <- subset(AveVVI_vs_AveSal, Marsh_Class == "Fresh")

Fresh_plot <- ggplot(Fresh,aes(x=veg_year,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Year", y= "Average Salinity") + 
  guides(color=guide_legend("Marsh Type"), shape = guide_legend("Marsh Type"))
Fresh_plot

###########
Intermediate <- subset(AveVVI_vs_AveSal, Marsh_Class == "Intermediate")

Intermediate_plot <- ggplot(Intermediate,aes(x=veg_year,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Year", y= "Average Salinity") + 
  guides(color=guide_legend("Marsh Type"), shape = guide_legend("Marsh Type"))
Intermediate_plot

###########
Saline <- subset(AveVVI_vs_AveSal, Marsh_Class == "Saline")

Saline_plot <- ggplot(Saline,aes(x=veg_year,y=Average_Salinity)) +
  geom_point(aes(colour= Marsh_Class, shape = Marsh_Class), alpha = 1, size = 3) + 
  labs(x="Year", y= "Average Salinity") + 
  guides(color=guide_legend("Marsh Type"), shape = guide_legend("Marsh Type"))
Saline_plot

grid.arrange(Brackish_plot, Fresh_plot ,Intermediate_plot, Saline_plot, nrow = 2)
```

