```{r}
defaultdir <- getwd()
dir.create("graphs")
# "/graphs/"
# setwd(paste(defaultdir,"/graphs/", sep = ""))
dir.create("tables")
# setwd(paste(defaultdir,"/tables/", sep = ""))


```

```{r, loading packages, include=TRUE, echo=FALSE}
#Adding the required packages for this file. Don't change the current order, and add new packages to the first.
packages <- c(
  "ggplot2", 
  "tidyverse", 
  "dplyr",
  "corrplot",
  "Hmisc"
  ) 
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
  lapply(packages, library, character.only = TRUE)
} else {
  lapply(packages, library, character.only = TRUE)
}
#Adding the required packages for this file. Don't change the current order, and add new packages to the first.

```

```{r}
setwd(defaultdir)
Fake2 <- read.csv(paste(defaultdir,"/data/", "Fake_2.csv",sep=""),
                          header = TRUE,sep = ",")
Fake_plot2 <- ggplot(Fake2) + 
  geom_bar(aes(x = Year, y = Frequency), stat ="identity", position="dodge") + 
  geom_line(aes(Year, Average_VegetationVolum_for_all/1000), size = 1.5, color="red", group = 1) + 
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Relative humidity [%]"))
  
  
  
Fake_plot2

geom_col(aes(Year, Frequency), size = 1, color = "darkblue", fill = "white") +
scale_y_continuous(sec.axis = sec_axis(~ .*1000, name = "Average_VegetationVolum_for_all"))

```



